
spring:
#  配置连接mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doms
#    url: jdbc:mysql://localhost:3306/doms1
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  #    password: Mxd99934179.
#  清除缓存，实现热部署(修改了html后不用重启，刷新页面就能看到效果。)
  thymeleaf:
    cache: false



mybatis:
#  开启在springboot中打印log日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    为MyBatis引用的实体类自定义别名.
  type-aliases-package: com.luo.doms.entity
#  扫描Mapper接口对应的XML文件
  mapper-locations: classpath:**/mapper/*.xml


#设置com.usc.mapper包下的日志等级为debug级别
logging:
  level:
    com:
      usc:
        mapper: debug



# PageHelper 分页插件配置
pagehelper:
#  指定数据库，不指定的话会默认自动检测数据库类型
  helper-dialect: mysql
#  启动分页合理化。如果启用，当 pagenum < 1 时，会自动查询第一页的数据，
#  当 pagenum > pges 时，自动查询最后一页数据；
  reasonable: true
#  默认为 false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
#  用于从对象中根据属性名取值
  params: count=countsql


server:
  port: 80